/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatusRouteImport } from './routes/status'
import { Route as InvitationsRouteImport } from './routes/invitations'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding/index'
import { Route as OnboardingUserRouteImport } from './routes/onboarding/user'
import { Route as OnboardingStep1RouteImport } from './routes/onboarding/step-1'
import { Route as OnboardingConsentRouteImport } from './routes/onboarding/consent'
import { Route as OnboardingCompanyRouteImport } from './routes/onboarding/company'
import { Route as InviteAcceptRouteImport } from './routes/invite/accept'
import { Route as AuthVerifyEmailRouteImport } from './routes/_auth/verify-email'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthSigninRouteImport } from './routes/_auth/signin'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as AppSelectOrganizationRouteImport } from './routes/_app/select-organization'
import { Route as AppExampleRouteImport } from './routes/_app/example'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as devDesignPreviewRouteImport } from './routes/(dev)/design-preview'
import { Route as devDashboardPreviewRouteImport } from './routes/(dev)/dashboard-preview'
import { Route as AppSettingsRouteRouteImport } from './routes/_app/settings/route'
import { Route as AppContactsIndexRouteImport } from './routes/_app/contacts.index'
import { Route as AppCatalogueIndexRouteImport } from './routes/_app/catalogue.index'
import { Route as AppSettingsTeamRouteImport } from './routes/_app/settings/team'
import { Route as AppSettingsProfileRouteImport } from './routes/_app/settings/profile'
import { Route as AppSettingsOrganizationRouteImport } from './routes/_app/settings/organization'
import { Route as AppSettingsModulesRouteImport } from './routes/_app/settings/modules'
import { Route as AppSettingsEstablishmentsRouteImport } from './routes/_app/settings/establishments'
import { Route as AppSettingsBillingRouteImport } from './routes/_app/settings/billing'
import { Route as AppSettingsAuditLogRouteImport } from './routes/_app/settings/audit-log'
import { Route as AppContactsContactIdRouteImport } from './routes/_app/contacts.$contactId'
import { Route as AppCatalogueCategoriesRouteImport } from './routes/_app/catalogue.categories'
import { Route as AppCatalogueProductIdRouteImport } from './routes/_app/catalogue.$productId'
import { Route as AppSettingsTeamRolesRouteImport } from './routes/_app/settings/team_.roles'
import { Route as AppSettingsSecuritySessionsRouteImport } from './routes/_app/settings/security/sessions'
import { Route as AppSettingsSecurity2faRouteImport } from './routes/_app/settings/security/2fa'
import { Route as AppSettingsEstablishmentsEstablishmentIdRouteImport } from './routes/_app/settings/establishments_.$establishmentId'
import { Route as AppSettingsBillingPlansRouteImport } from './routes/_app/settings/billing_.plans'
import { Route as AppSettingsTeamRolesRoleIdRouteImport } from './routes/_app/settings/team_.roles_.$roleId'

const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitationsRoute = InvitationsRouteImport.update({
  id: '/invitations',
  path: '/invitations',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingUserRoute = OnboardingUserRouteImport.update({
  id: '/onboarding/user',
  path: '/onboarding/user',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingStep1Route = OnboardingStep1RouteImport.update({
  id: '/onboarding/step-1',
  path: '/onboarding/step-1',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingConsentRoute = OnboardingConsentRouteImport.update({
  id: '/onboarding/consent',
  path: '/onboarding/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingCompanyRoute = OnboardingCompanyRouteImport.update({
  id: '/onboarding/company',
  path: '/onboarding/company',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteAcceptRoute = InviteAcceptRouteImport.update({
  id: '/invite/accept',
  path: '/invite/accept',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AppSelectOrganizationRoute = AppSelectOrganizationRouteImport.update({
  id: '/select-organization',
  path: '/select-organization',
  getParentRoute: () => AppRoute,
} as any)
const AppExampleRoute = AppExampleRouteImport.update({
  id: '/example',
  path: '/example',
  getParentRoute: () => AppRoute,
} as any).lazy(() => import('./routes/_app/example.lazy').then((d) => d.Route))
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const devDesignPreviewRoute = devDesignPreviewRouteImport.update({
  id: '/(dev)/design-preview',
  path: '/design-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const devDashboardPreviewRoute = devDashboardPreviewRouteImport.update({
  id: '/(dev)/dashboard-preview',
  path: '/dashboard-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRouteRoute = AppSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppContactsIndexRoute = AppContactsIndexRouteImport.update({
  id: '/contacts/',
  path: '/contacts/',
  getParentRoute: () => AppRoute,
} as any)
const AppCatalogueIndexRoute = AppCatalogueIndexRouteImport.update({
  id: '/catalogue/',
  path: '/catalogue/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsTeamRoute = AppSettingsTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSettingsProfileRoute = AppSettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSettingsOrganizationRoute = AppSettingsOrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSettingsModulesRoute = AppSettingsModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSettingsEstablishmentsRoute =
  AppSettingsEstablishmentsRouteImport.update({
    id: '/establishments',
    path: '/establishments',
    getParentRoute: () => AppSettingsRouteRoute,
  } as any)
const AppSettingsBillingRoute = AppSettingsBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSettingsAuditLogRoute = AppSettingsAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppContactsContactIdRoute = AppContactsContactIdRouteImport.update({
  id: '/contacts/$contactId',
  path: '/contacts/$contactId',
  getParentRoute: () => AppRoute,
} as any)
const AppCatalogueCategoriesRoute = AppCatalogueCategoriesRouteImport.update({
  id: '/catalogue/categories',
  path: '/catalogue/categories',
  getParentRoute: () => AppRoute,
} as any)
const AppCatalogueProductIdRoute = AppCatalogueProductIdRouteImport.update({
  id: '/catalogue/$productId',
  path: '/catalogue/$productId',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsTeamRolesRoute = AppSettingsTeamRolesRouteImport.update({
  id: '/team_/roles',
  path: '/team/roles',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSettingsSecuritySessionsRoute =
  AppSettingsSecuritySessionsRouteImport.update({
    id: '/security/sessions',
    path: '/security/sessions',
    getParentRoute: () => AppSettingsRouteRoute,
  } as any)
const AppSettingsSecurity2faRoute = AppSettingsSecurity2faRouteImport.update({
  id: '/security/2fa',
  path: '/security/2fa',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSettingsEstablishmentsEstablishmentIdRoute =
  AppSettingsEstablishmentsEstablishmentIdRouteImport.update({
    id: '/establishments_/$establishmentId',
    path: '/establishments/$establishmentId',
    getParentRoute: () => AppSettingsRouteRoute,
  } as any)
const AppSettingsBillingPlansRoute = AppSettingsBillingPlansRouteImport.update({
  id: '/billing_/plans',
  path: '/billing/plans',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSettingsTeamRolesRoleIdRoute =
  AppSettingsTeamRolesRoleIdRouteImport.update({
    id: '/team_/roles_/$roleId',
    path: '/team/roles/$roleId',
    getParentRoute: () => AppSettingsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/invitations': typeof InvitationsRoute
  '/status': typeof StatusRoute
  '/settings': typeof AppSettingsRouteRouteWithChildren
  '/dashboard-preview': typeof devDashboardPreviewRoute
  '/design-preview': typeof devDesignPreviewRoute
  '/dashboard': typeof AppDashboardRoute
  '/example': typeof AppExampleRoute
  '/select-organization': typeof AppSelectOrganizationRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/signin': typeof AuthSigninRoute
  '/signup': typeof AuthSignupRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/invite/accept': typeof InviteAcceptRoute
  '/onboarding/company': typeof OnboardingCompanyRoute
  '/onboarding/consent': typeof OnboardingConsentRoute
  '/onboarding/step-1': typeof OnboardingStep1Route
  '/onboarding/user': typeof OnboardingUserRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/catalogue/$productId': typeof AppCatalogueProductIdRoute
  '/catalogue/categories': typeof AppCatalogueCategoriesRoute
  '/contacts/$contactId': typeof AppContactsContactIdRoute
  '/settings/audit-log': typeof AppSettingsAuditLogRoute
  '/settings/billing': typeof AppSettingsBillingRoute
  '/settings/establishments': typeof AppSettingsEstablishmentsRoute
  '/settings/modules': typeof AppSettingsModulesRoute
  '/settings/organization': typeof AppSettingsOrganizationRoute
  '/settings/profile': typeof AppSettingsProfileRoute
  '/settings/team': typeof AppSettingsTeamRoute
  '/catalogue/': typeof AppCatalogueIndexRoute
  '/contacts/': typeof AppContactsIndexRoute
  '/settings/billing/plans': typeof AppSettingsBillingPlansRoute
  '/settings/establishments/$establishmentId': typeof AppSettingsEstablishmentsEstablishmentIdRoute
  '/settings/security/2fa': typeof AppSettingsSecurity2faRoute
  '/settings/security/sessions': typeof AppSettingsSecuritySessionsRoute
  '/settings/team/roles': typeof AppSettingsTeamRolesRoute
  '/settings/team/roles/$roleId': typeof AppSettingsTeamRolesRoleIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/invitations': typeof InvitationsRoute
  '/status': typeof StatusRoute
  '/settings': typeof AppSettingsRouteRouteWithChildren
  '/dashboard-preview': typeof devDashboardPreviewRoute
  '/design-preview': typeof devDesignPreviewRoute
  '/dashboard': typeof AppDashboardRoute
  '/example': typeof AppExampleRoute
  '/select-organization': typeof AppSelectOrganizationRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/signin': typeof AuthSigninRoute
  '/signup': typeof AuthSignupRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/invite/accept': typeof InviteAcceptRoute
  '/onboarding/company': typeof OnboardingCompanyRoute
  '/onboarding/consent': typeof OnboardingConsentRoute
  '/onboarding/step-1': typeof OnboardingStep1Route
  '/onboarding/user': typeof OnboardingUserRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/catalogue/$productId': typeof AppCatalogueProductIdRoute
  '/catalogue/categories': typeof AppCatalogueCategoriesRoute
  '/contacts/$contactId': typeof AppContactsContactIdRoute
  '/settings/audit-log': typeof AppSettingsAuditLogRoute
  '/settings/billing': typeof AppSettingsBillingRoute
  '/settings/establishments': typeof AppSettingsEstablishmentsRoute
  '/settings/modules': typeof AppSettingsModulesRoute
  '/settings/organization': typeof AppSettingsOrganizationRoute
  '/settings/profile': typeof AppSettingsProfileRoute
  '/settings/team': typeof AppSettingsTeamRoute
  '/catalogue': typeof AppCatalogueIndexRoute
  '/contacts': typeof AppContactsIndexRoute
  '/settings/billing/plans': typeof AppSettingsBillingPlansRoute
  '/settings/establishments/$establishmentId': typeof AppSettingsEstablishmentsEstablishmentIdRoute
  '/settings/security/2fa': typeof AppSettingsSecurity2faRoute
  '/settings/security/sessions': typeof AppSettingsSecuritySessionsRoute
  '/settings/team/roles': typeof AppSettingsTeamRolesRoute
  '/settings/team/roles/$roleId': typeof AppSettingsTeamRolesRoleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/invitations': typeof InvitationsRoute
  '/status': typeof StatusRoute
  '/_app/settings': typeof AppSettingsRouteRouteWithChildren
  '/(dev)/dashboard-preview': typeof devDashboardPreviewRoute
  '/(dev)/design-preview': typeof devDesignPreviewRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/example': typeof AppExampleRoute
  '/_app/select-organization': typeof AppSelectOrganizationRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/signin': typeof AuthSigninRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_auth/verify-email': typeof AuthVerifyEmailRoute
  '/invite/accept': typeof InviteAcceptRoute
  '/onboarding/company': typeof OnboardingCompanyRoute
  '/onboarding/consent': typeof OnboardingConsentRoute
  '/onboarding/step-1': typeof OnboardingStep1Route
  '/onboarding/user': typeof OnboardingUserRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/_app/catalogue/$productId': typeof AppCatalogueProductIdRoute
  '/_app/catalogue/categories': typeof AppCatalogueCategoriesRoute
  '/_app/contacts/$contactId': typeof AppContactsContactIdRoute
  '/_app/settings/audit-log': typeof AppSettingsAuditLogRoute
  '/_app/settings/billing': typeof AppSettingsBillingRoute
  '/_app/settings/establishments': typeof AppSettingsEstablishmentsRoute
  '/_app/settings/modules': typeof AppSettingsModulesRoute
  '/_app/settings/organization': typeof AppSettingsOrganizationRoute
  '/_app/settings/profile': typeof AppSettingsProfileRoute
  '/_app/settings/team': typeof AppSettingsTeamRoute
  '/_app/catalogue/': typeof AppCatalogueIndexRoute
  '/_app/contacts/': typeof AppContactsIndexRoute
  '/_app/settings/billing_/plans': typeof AppSettingsBillingPlansRoute
  '/_app/settings/establishments_/$establishmentId': typeof AppSettingsEstablishmentsEstablishmentIdRoute
  '/_app/settings/security/2fa': typeof AppSettingsSecurity2faRoute
  '/_app/settings/security/sessions': typeof AppSettingsSecuritySessionsRoute
  '/_app/settings/team_/roles': typeof AppSettingsTeamRolesRoute
  '/_app/settings/team_/roles_/$roleId': typeof AppSettingsTeamRolesRoleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/invitations'
    | '/status'
    | '/settings'
    | '/dashboard-preview'
    | '/design-preview'
    | '/dashboard'
    | '/example'
    | '/select-organization'
    | '/forgot-password'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/verify-email'
    | '/invite/accept'
    | '/onboarding/company'
    | '/onboarding/consent'
    | '/onboarding/step-1'
    | '/onboarding/user'
    | '/onboarding/'
    | '/catalogue/$productId'
    | '/catalogue/categories'
    | '/contacts/$contactId'
    | '/settings/audit-log'
    | '/settings/billing'
    | '/settings/establishments'
    | '/settings/modules'
    | '/settings/organization'
    | '/settings/profile'
    | '/settings/team'
    | '/catalogue/'
    | '/contacts/'
    | '/settings/billing/plans'
    | '/settings/establishments/$establishmentId'
    | '/settings/security/2fa'
    | '/settings/security/sessions'
    | '/settings/team/roles'
    | '/settings/team/roles/$roleId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/invitations'
    | '/status'
    | '/settings'
    | '/dashboard-preview'
    | '/design-preview'
    | '/dashboard'
    | '/example'
    | '/select-organization'
    | '/forgot-password'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/verify-email'
    | '/invite/accept'
    | '/onboarding/company'
    | '/onboarding/consent'
    | '/onboarding/step-1'
    | '/onboarding/user'
    | '/onboarding'
    | '/catalogue/$productId'
    | '/catalogue/categories'
    | '/contacts/$contactId'
    | '/settings/audit-log'
    | '/settings/billing'
    | '/settings/establishments'
    | '/settings/modules'
    | '/settings/organization'
    | '/settings/profile'
    | '/settings/team'
    | '/catalogue'
    | '/contacts'
    | '/settings/billing/plans'
    | '/settings/establishments/$establishmentId'
    | '/settings/security/2fa'
    | '/settings/security/sessions'
    | '/settings/team/roles'
    | '/settings/team/roles/$roleId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/invitations'
    | '/status'
    | '/_app/settings'
    | '/(dev)/dashboard-preview'
    | '/(dev)/design-preview'
    | '/_app/dashboard'
    | '/_app/example'
    | '/_app/select-organization'
    | '/_auth/forgot-password'
    | '/_auth/reset-password'
    | '/_auth/signin'
    | '/_auth/signup'
    | '/_auth/verify-email'
    | '/invite/accept'
    | '/onboarding/company'
    | '/onboarding/consent'
    | '/onboarding/step-1'
    | '/onboarding/user'
    | '/onboarding/'
    | '/_app/catalogue/$productId'
    | '/_app/catalogue/categories'
    | '/_app/contacts/$contactId'
    | '/_app/settings/audit-log'
    | '/_app/settings/billing'
    | '/_app/settings/establishments'
    | '/_app/settings/modules'
    | '/_app/settings/organization'
    | '/_app/settings/profile'
    | '/_app/settings/team'
    | '/_app/catalogue/'
    | '/_app/contacts/'
    | '/_app/settings/billing_/plans'
    | '/_app/settings/establishments_/$establishmentId'
    | '/_app/settings/security/2fa'
    | '/_app/settings/security/sessions'
    | '/_app/settings/team_/roles'
    | '/_app/settings/team_/roles_/$roleId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  InvitationsRoute: typeof InvitationsRoute
  StatusRoute: typeof StatusRoute
  devDashboardPreviewRoute: typeof devDashboardPreviewRoute
  devDesignPreviewRoute: typeof devDesignPreviewRoute
  InviteAcceptRoute: typeof InviteAcceptRoute
  OnboardingCompanyRoute: typeof OnboardingCompanyRoute
  OnboardingConsentRoute: typeof OnboardingConsentRoute
  OnboardingStep1Route: typeof OnboardingStep1Route
  OnboardingUserRoute: typeof OnboardingUserRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitations': {
      id: '/invitations'
      path: '/invitations'
      fullPath: '/invitations'
      preLoaderRoute: typeof InvitationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/user': {
      id: '/onboarding/user'
      path: '/onboarding/user'
      fullPath: '/onboarding/user'
      preLoaderRoute: typeof OnboardingUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/step-1': {
      id: '/onboarding/step-1'
      path: '/onboarding/step-1'
      fullPath: '/onboarding/step-1'
      preLoaderRoute: typeof OnboardingStep1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/consent': {
      id: '/onboarding/consent'
      path: '/onboarding/consent'
      fullPath: '/onboarding/consent'
      preLoaderRoute: typeof OnboardingConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/company': {
      id: '/onboarding/company'
      path: '/onboarding/company'
      fullPath: '/onboarding/company'
      preLoaderRoute: typeof OnboardingCompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/accept': {
      id: '/invite/accept'
      path: '/invite/accept'
      fullPath: '/invite/accept'
      preLoaderRoute: typeof InviteAcceptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/verify-email': {
      id: '/_auth/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/signin': {
      id: '/_auth/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/select-organization': {
      id: '/_app/select-organization'
      path: '/select-organization'
      fullPath: '/select-organization'
      preLoaderRoute: typeof AppSelectOrganizationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/example': {
      id: '/_app/example'
      path: '/example'
      fullPath: '/example'
      preLoaderRoute: typeof AppExampleRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/(dev)/design-preview': {
      id: '/(dev)/design-preview'
      path: '/design-preview'
      fullPath: '/design-preview'
      preLoaderRoute: typeof devDesignPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dev)/dashboard-preview': {
      id: '/(dev)/dashboard-preview'
      path: '/dashboard-preview'
      fullPath: '/dashboard-preview'
      preLoaderRoute: typeof devDashboardPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contacts/': {
      id: '/_app/contacts/'
      path: '/contacts'
      fullPath: '/contacts/'
      preLoaderRoute: typeof AppContactsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/catalogue/': {
      id: '/_app/catalogue/'
      path: '/catalogue'
      fullPath: '/catalogue/'
      preLoaderRoute: typeof AppCatalogueIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/team': {
      id: '/_app/settings/team'
      path: '/team'
      fullPath: '/settings/team'
      preLoaderRoute: typeof AppSettingsTeamRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/settings/profile': {
      id: '/_app/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AppSettingsProfileRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/settings/organization': {
      id: '/_app/settings/organization'
      path: '/organization'
      fullPath: '/settings/organization'
      preLoaderRoute: typeof AppSettingsOrganizationRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/settings/modules': {
      id: '/_app/settings/modules'
      path: '/modules'
      fullPath: '/settings/modules'
      preLoaderRoute: typeof AppSettingsModulesRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/settings/establishments': {
      id: '/_app/settings/establishments'
      path: '/establishments'
      fullPath: '/settings/establishments'
      preLoaderRoute: typeof AppSettingsEstablishmentsRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/settings/billing': {
      id: '/_app/settings/billing'
      path: '/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof AppSettingsBillingRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/settings/audit-log': {
      id: '/_app/settings/audit-log'
      path: '/audit-log'
      fullPath: '/settings/audit-log'
      preLoaderRoute: typeof AppSettingsAuditLogRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/contacts/$contactId': {
      id: '/_app/contacts/$contactId'
      path: '/contacts/$contactId'
      fullPath: '/contacts/$contactId'
      preLoaderRoute: typeof AppContactsContactIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/catalogue/categories': {
      id: '/_app/catalogue/categories'
      path: '/catalogue/categories'
      fullPath: '/catalogue/categories'
      preLoaderRoute: typeof AppCatalogueCategoriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/catalogue/$productId': {
      id: '/_app/catalogue/$productId'
      path: '/catalogue/$productId'
      fullPath: '/catalogue/$productId'
      preLoaderRoute: typeof AppCatalogueProductIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/team_/roles': {
      id: '/_app/settings/team_/roles'
      path: '/team/roles'
      fullPath: '/settings/team/roles'
      preLoaderRoute: typeof AppSettingsTeamRolesRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/settings/security/sessions': {
      id: '/_app/settings/security/sessions'
      path: '/security/sessions'
      fullPath: '/settings/security/sessions'
      preLoaderRoute: typeof AppSettingsSecuritySessionsRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/settings/security/2fa': {
      id: '/_app/settings/security/2fa'
      path: '/security/2fa'
      fullPath: '/settings/security/2fa'
      preLoaderRoute: typeof AppSettingsSecurity2faRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/settings/establishments_/$establishmentId': {
      id: '/_app/settings/establishments_/$establishmentId'
      path: '/establishments/$establishmentId'
      fullPath: '/settings/establishments/$establishmentId'
      preLoaderRoute: typeof AppSettingsEstablishmentsEstablishmentIdRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/settings/billing_/plans': {
      id: '/_app/settings/billing_/plans'
      path: '/billing/plans'
      fullPath: '/settings/billing/plans'
      preLoaderRoute: typeof AppSettingsBillingPlansRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/settings/team_/roles_/$roleId': {
      id: '/_app/settings/team_/roles_/$roleId'
      path: '/team/roles/$roleId'
      fullPath: '/settings/team/roles/$roleId'
      preLoaderRoute: typeof AppSettingsTeamRolesRoleIdRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
  }
}

interface AppSettingsRouteRouteChildren {
  AppSettingsAuditLogRoute: typeof AppSettingsAuditLogRoute
  AppSettingsBillingRoute: typeof AppSettingsBillingRoute
  AppSettingsEstablishmentsRoute: typeof AppSettingsEstablishmentsRoute
  AppSettingsModulesRoute: typeof AppSettingsModulesRoute
  AppSettingsOrganizationRoute: typeof AppSettingsOrganizationRoute
  AppSettingsProfileRoute: typeof AppSettingsProfileRoute
  AppSettingsTeamRoute: typeof AppSettingsTeamRoute
  AppSettingsBillingPlansRoute: typeof AppSettingsBillingPlansRoute
  AppSettingsEstablishmentsEstablishmentIdRoute: typeof AppSettingsEstablishmentsEstablishmentIdRoute
  AppSettingsSecurity2faRoute: typeof AppSettingsSecurity2faRoute
  AppSettingsSecuritySessionsRoute: typeof AppSettingsSecuritySessionsRoute
  AppSettingsTeamRolesRoute: typeof AppSettingsTeamRolesRoute
  AppSettingsTeamRolesRoleIdRoute: typeof AppSettingsTeamRolesRoleIdRoute
}

const AppSettingsRouteRouteChildren: AppSettingsRouteRouteChildren = {
  AppSettingsAuditLogRoute: AppSettingsAuditLogRoute,
  AppSettingsBillingRoute: AppSettingsBillingRoute,
  AppSettingsEstablishmentsRoute: AppSettingsEstablishmentsRoute,
  AppSettingsModulesRoute: AppSettingsModulesRoute,
  AppSettingsOrganizationRoute: AppSettingsOrganizationRoute,
  AppSettingsProfileRoute: AppSettingsProfileRoute,
  AppSettingsTeamRoute: AppSettingsTeamRoute,
  AppSettingsBillingPlansRoute: AppSettingsBillingPlansRoute,
  AppSettingsEstablishmentsEstablishmentIdRoute:
    AppSettingsEstablishmentsEstablishmentIdRoute,
  AppSettingsSecurity2faRoute: AppSettingsSecurity2faRoute,
  AppSettingsSecuritySessionsRoute: AppSettingsSecuritySessionsRoute,
  AppSettingsTeamRolesRoute: AppSettingsTeamRolesRoute,
  AppSettingsTeamRolesRoleIdRoute: AppSettingsTeamRolesRoleIdRoute,
}

const AppSettingsRouteRouteWithChildren =
  AppSettingsRouteRoute._addFileChildren(AppSettingsRouteRouteChildren)

interface AppRouteChildren {
  AppSettingsRouteRoute: typeof AppSettingsRouteRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppExampleRoute: typeof AppExampleRoute
  AppSelectOrganizationRoute: typeof AppSelectOrganizationRoute
  AppCatalogueProductIdRoute: typeof AppCatalogueProductIdRoute
  AppCatalogueCategoriesRoute: typeof AppCatalogueCategoriesRoute
  AppContactsContactIdRoute: typeof AppContactsContactIdRoute
  AppCatalogueIndexRoute: typeof AppCatalogueIndexRoute
  AppContactsIndexRoute: typeof AppContactsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSettingsRouteRoute: AppSettingsRouteRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppExampleRoute: AppExampleRoute,
  AppSelectOrganizationRoute: AppSelectOrganizationRoute,
  AppCatalogueProductIdRoute: AppCatalogueProductIdRoute,
  AppCatalogueCategoriesRoute: AppCatalogueCategoriesRoute,
  AppContactsContactIdRoute: AppContactsContactIdRoute,
  AppCatalogueIndexRoute: AppCatalogueIndexRoute,
  AppContactsIndexRoute: AppContactsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  InvitationsRoute: InvitationsRoute,
  StatusRoute: StatusRoute,
  devDashboardPreviewRoute: devDashboardPreviewRoute,
  devDesignPreviewRoute: devDesignPreviewRoute,
  InviteAcceptRoute: InviteAcceptRoute,
  OnboardingCompanyRoute: OnboardingCompanyRoute,
  OnboardingConsentRoute: OnboardingConsentRoute,
  OnboardingStep1Route: OnboardingStep1Route,
  OnboardingUserRoute: OnboardingUserRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
