// Generated by Wrangler by running `wrangler types --x-include-runtime=false`

interface Env {
  SESSIONS_KV: KVNamespace;
  BETTER_AUTH_URL:
    | 'http://localhost:9187'
    | 'https://api.staging.__PROJECT_SLUG__.com'
    | 'https://api.__PROJECT_SLUG__.com';
  APP_URL: 'http://localhost:9100' | 'https://staging.__PROJECT_SLUG__.com' | 'https://app.__PROJECT_SLUG__.com';
  ENVIRONMENT: string;
  DATABASE_URL: string;
  SENTRY_DSN: string;
  AXIOM_TOKEN: string;
  AXIOM_DATASET: string;
  BETTER_AUTH_SECRET: string;
  RESEND_API_KEY: string;
  RESEND_FROM_EMAIL: string;
  STRIPE_SECRET_KEY: string;
  STRIPE_PRICE_IDS_JSON: string;
}
