#!/usr/bin/env node
/**
 * retheme.mjs — re-theme an ALREADY-GENERATED `core` project in place.
 *
 * Re-derives the project identity (scope / name / display) from the target repo,
 * builds a theme spec from flags or an imported Claude Design bundle, and applies
 * it (rewrites tokens.css, copies fonts/logos/favicon, recolors manifest).
 *
 * Usage:
 *   node retheme.mjs [projectDir] [theme flags] [--display <Name>] [--yes]
 *   e.g. node retheme.mjs . --theme zinc-violet
 *        node retheme.mjs ./acme --design-url https://api.anthropic.com/v1/design/h/<hash>
 *        node retheme.mjs ./acme --primary '#334155' --accent '#3b82f6' --mode dark
 */
import { readFileSync, existsSync } from 'node:fs';
import { join, dirname, resolve, isAbsolute } from 'node:path';
import { fileURLToPath } from 'node:url';
import { buildThemeSpec } from './theme-resolve.mjs';
import { applyTheme } from './apply-theme.mjs';

const __dirname = dirname(fileURLToPath(import.meta.url));
const argv = process.argv.slice(2);
const flag = (f) => argv.includes(f);
const val = (f) => { const i = argv.indexOf(f); return i !== -1 && argv[i + 1] ? argv[i + 1] : undefined; };
const C = { dim: (s) => `\x1b[2m${s}\x1b[0m`, g: (s) => `\x1b[32m${s}\x1b[0m`, r: (s) => `\x1b[31m${s}\x1b[0m`, y: (s) => `\x1b[33m${s}\x1b[0m` };

const positional = argv.find((a) => !a.startsWith('-') && argv[argv.indexOf(a) - 1]?.startsWith('--') !== true);
const dir = isAbsolute(positional || '.') ? (positional || '.') : resolve(process.cwd(), positional || '.');
const YES = flag('--yes') || flag('-y');

function fail(m) { console.error(`\n  ${C.r('✖')} ${m}\n`); process.exit(1); }
const readJson = (p) => JSON.parse(readFileSync(p, 'utf8'));

// ── identity ──
const rootPkgPath = join(dir, 'package.json');
if (!existsSync(rootPkgPath)) fail(`No package.json in ${dir} — is this a generated project root?`);
const name = readJson(rootPkgPath).name;
if (!name) fail('Could not read project name from package.json.');

function detectScope() {
  for (const p of ['packages/config/package.json', 'apps/suite/package.json', 'packages/ui/package.json']) {
    const fp = join(dir, p);
    if (existsSync(fp)) { const m = (readJson(fp).name || '').match(/^@([^/]+)\//); if (m) return m[1]; }
  }
  return name;
}
const scope = detectScope();
let display = val('--display');
if (!display) {
  const man = join(dir, 'apps/suite/public/manifest.webmanifest');
  if (existsSync(man)) { try { display = readJson(man).short_name; } catch { /* ignore */ } }
}
if (!display) display = name.charAt(0).toUpperCase() + name.slice(1).replace(/-/g, '');

// ── guard: only re-theme generated `core` token files ──
const tokensPath = join(dir, 'packages/ui/src/styles/tokens.css');
if (!existsSync(tokensPath)) fail(`${tokensPath} not found — re-theming targets a generated core project.`);
const tokens = readFileSync(tokensPath, 'utf8');
const looksGenerated = /create-koralab-saas|--color-base-900/.test(tokens);
if (!looksGenerated && !YES) {
  fail(`This tokens.css doesn't look generated by the theme engine (likely a 'full'-variant or hand-edited project).\n     Re-theming will OVERWRITE it. Re-run with --yes to proceed.`);
}
if (!looksGenerated) console.error(`  ${C.y('⚠')} tokens.css will be overwritten (not recognized as generated).`);

// ── build + apply ──
console.log(`\n  ${C.dim('re-theme')} ${name} ${C.dim(`(@${scope}, "${display}") at ${dir}`)}`);
let spec;
try { spec = buildThemeSpec({ val: (f) => val(f), selfDir: __dirname }).spec; }
catch (e) { fail(e.message); }
applyTheme(dir, spec, { scope, name, display });

const fontLabel = typeof spec.font === 'string' ? spec.font : 'imported';
const radiusLabel = typeof spec.radius === 'string' ? spec.radius : 'custom';
console.log(`  ${C.g('✓')} theme applied — preset=${spec.preset} · font=${fontLabel} · radius=${radiusLabel} · mode=${spec.mode}`);
console.log(`  ${C.dim('tokens.css regenerated. Run `pnpm dev` or `pnpm build` to see it.')}\n`);
